---
services:
  lidarr:
    image: grafana/loki:latest
    container_name: loki
    volumes:
      - ./loki-config.yml:/etc/loki/loki-config.yaml
    ports:
      - 3100:3100
    restart: unless-stopped
