---
version: "3"
services:
  lidarr:
    image: grafana/loki:latest
    container_name: loki
    volumes:
      - /opt/loki/config:/home/loki/config
    ports:
      - 3100:3100
    command: -config.file=/home/loki/config/config.yml
    restart: unless-stopped
