---
volumes:
  overseerr:
    driver: local
services:
  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - overseerr:/config
      - /mnt/media:/media #optional
    ports:
      - 5055:5055
    restart: unless-stopped
