---
volumes:
  prowlarr:
    driver: local
services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
