services:
  uptimekuma:
    image: docker.io/louislam/uptime-kuma:1.23.13
    container_name: uptimekuma
    ports:
      - 3001:3001
    volumes:
      - ${UPTIME_KUMA_DATA_DIR:-/opt/docker/uptime-kuma/data}:/app/data
    restart: unless-stopped
