---
volumes:
  sabnzbd:
    driver: local
services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - sabnzbd:/config
      - /mnt/media:/media #optional
    ports:
      - 8080:8080
    restart: unless-stopped
