---
version: "3"
services:
  load-balancer:
    image: nginx:latest
    volumes:
      - /opt/mimir/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - "mimir-1"
      - "mimir-2"
      - "mimir-3"
    ports:
      - 9009:9009

  mimir-1:
    image: grafana/mimir:latest
    command: -config.file=/home/mimir/config.yml
    hostname: mimir-1
    volumes:
      - /opt/mimir/config.yml:/home/mimir/config.yml
      - /opt/mimir/alertmanager-fallback-config.yml:/home/mimir/alertmanager-fallback-config.yml
      - mimir-1-data:/data
    restart: unless-stopped

  mimir-2:
    image: grafana/mimir:latest
    command: -config.file=/home/mimir/config.yml
    hostname: mimir-2
    volumes:
      - /opt/mimir/config.yml:/home/mimir/config.yml
      - /opt/mimir/alertmanager-fallback-config.yml:/home/mimir/alertmanager-fallback-config.yml
      - mimir-2-data:/data
    restart: unless-stopped

  mimir-3:
    image: grafana/mimir:latest
    command: -config.file=/home/mimir/config.yml
    hostname: mimir-3
    volumes:
      - /opt/mimir/config.yml:/home/mimir/config.yml
      - /opt/mimir/alertmanager-fallback-config.yml:/home/mimir/alertmanager-fallback-config.yml
      - mimir-3-data:/data
    restart: unless-stopped

volumes:
  mimir-1-data:
  mimir-2-data:
  mimir-3-data:
