---
volumes:
  grafana-data:
    driver: local
services:
  grafana:
    image: docker.io/grafana/grafana-oss:11.1.0
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana.ini:/etc/grafana/grafana.ini
    environment:
      GF_SECURITY_ADMIN_USER: user
      GF_SECURITY_ADMIN_PASSWORD: 1234
    restart: unless-stopped
