---
volumes:
  radarr:
    driver: local
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - radarr:/config
      - /mnt/media:/media #optional
    ports:
      - 7878:7878
    restart: unless-stopped
