services:
  traefik-kop:
    image: "ghcr.io/jittering/traefik-kop:latest"
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - "REDIS_ADDR=${REDIS_SERVER_ADDRESS}:6379"
      - "BIND_IP=${BIND_ADDRESS}"
