services:
  redis:
    image: redis/redis-stack-server:7.2.0-v6
    container_name: redis
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]
    volumes:
      - redis_data:/data

volumes:
  redis_data:
