---
volumes:
  jellyseerr:
    driver: local
services:
  jellyseerr:
    container_name: jellyseerr
    image: fallenbagel/jellyseerr:latest
    ports:
      - 5055:5055
    volumes:
      - jellyseerr:/app/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    restart: unless-stopped
